### ISSUE TITLE
图像加载问题

### ISSUE THREAD

**Issue by shencexiang** [heicathei/gateway#1]
很棒的项目，有点小问题，画图图片无法正常加载，还有聊天建议功能没有

**Comment by heicathei** [comment]
只要代理能正常访问就都是正常的哦，我测试也没啥问题
![image](https://github.com/heicathei/gateway/assets/94883313/25682783-a778-4013-b41c-6a63592203a7)

**Comment by shencexiang** [comment]
![20240504_142225_edit_173976733964077](https://github.com/heicathei/gateway/assets/117926262/ce48880a-d48b-4908-af70-b43a95ebdf9e)
是这样的

**Comment by heicathei** [comment]
我测试正常哦
![image](https://github.com/heicathei/gateway/assets/94883313/f0b00381-942b-423a-862c-c04160f682e4)

**Comment by shencexiang** [comment]
谢谢，我是用在share做网关时出现的，我再仔细排查一下

**Comment by heicathei** [comment]
部署成功以后该服务既是网关也是一个镜像站，你可以尝试直接登录然后查看图片显示是否正常

**Comment by shencexiang** [comment]
奇怪，镜像站可以登录，以前的图片都能看到，但是发不了消息，转圈

**Comment by heicathei** [comment]
要么是代理不行，要么就是那个账号聊天接口是wss，具体可以去查看接口响应信息

**Comment by shencexiang** [comment]
好的，那wss还有解决方法吗？
